### ISSUE TITLE
Add court codes/IDs to every court JSON file

### ISSUE THREAD

**Issue by nonprofittechy** [GBLS/docassemble-MACourts#14]
Every court has an ID associated with it, which can be alpha numeric. We want to take those IDs and add this as metadata to each court in our current JSON files.

For now, I would probably add the ID as a key named "court_id" at the same parent level as name, etc.

Full list of IDs: https://www.mass.gov/info-details/trial-court-codes-numerical-listing

Here are the JSON files that need the IDs added:

- [ ] https://github.com/GBLS/docassemble-MACourts/blob/master/docassemble/MACourts/data/sources/bmc.json
- [ ] https://github.com/GBLS/docassemble-MACourts/blob/master/docassemble/MACourts/data/sources/district_courts.json
- [ ] https://github.com/GBLS/docassemble-MACourts/blob/master/docassemble/MACourts/data/sources/housing_courts.json
- [ ] https://github.com/GBLS/docassemble-MACourts/blob/master/docassemble/MACourts/data/sources/juvenile_courts.json
- [ ] https://github.com/GBLS/docassemble-MACourts/blob/master/docassemble/MACourts/data/sources/land_court.json
- [ ] https://github.com/GBLS/docassemble-MACourts/blob/master/docassemble/MACourts/data/sources/probate_and_family_courts.json
- [ ] https://github.com/GBLS/docassemble-MACourts/blob/master/docassemble/MACourts/data/sources/superior_courts.json

**Comment by cc271793784** [comment]
https://github.com/GBLS/docassemble-MACourts/blob/master/docassemble/MACourts/data/sources/land_court.json

The land court code could not be found on the mass.gov website.

**Comment by cc271793784** [comment]
Issue: For probate and family courts file, Brockton Probate and Family Court is not listed on the website as well.

**Comment by nonprofittechy** [comment]
Brockton Probate and Family is one of the locations of the Plymouth Probate and Family Court

**Comment by cc271793784** [comment]
> Brockton Probate and Family is one of the locations of the Plymouth Probate and Family Court

Got it, I've added this.

**Comment by cc271793784** [comment]
All courts files with court code added is in branch add_court_code -- docassemble -- MAcourts -- data --source.

**Comment by cc271793784** [comment]
Quick update: the previously bmc_addcode.json file has some issues (all code showing in 0). I've corrected it and all files are stored as the original name (without _addcode).
