### ISSUE TITLE
Add a way to load court ID from the court JSON file

### ISSUE THREAD

**Issue by nonprofittechy** [GBLS/docassemble-MACourts#15]
Edit the https://github.com/GBLS/docassemble-MACourts/blob/master/docassemble/MACourts/macourts.py file at the `load_courts_from_file` method. Around line https://github.com/GBLS/docassemble-MACourts/blob/master/docassemble/MACourts/macourts.py#L440 in the master as of this issue being created (may move around by the time this issue is acted on).

![image](https://user-images.githubusercontent.com/7645641/87965235-6dd18780-ca89-11ea-98b8-0a582f3e647d.png)

**Comment by plocket** [comment]
I think this means to add the `court_code` property to these objects.

**Comment by cc271793784** [comment]
The function has been modified by adding the court_code part and it works. It also Pass the test.
