### ISSUE TITLE
Add all of the "shimmed" courts into the appropriate JSON file for that court department

### ISSUE THREAD

**Issue by nonprofittechy** [GBLS/docassemble-MACourts#16]
We have two courts that are hardcoded in the Python file now. We should move those into the appropriate JSON files:

![image](https://user-images.githubusercontent.com/7645641/87965387-aa04e800-ca89-11ea-9027-d2bce5a216f9.png)

**Comment by cc271793784** [comment]
Note: Court codes also need to be added here

**Comment by cc271793784** [comment]
The files with 4 new courts and court code added are uploaded as housing_courts_addcode+add4new.json under the branch add_court_code -- docassemble -- MAcourts -- data --source
